name: Run pytest, flake8 and coverage

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout toy-robot-challenge source code
      uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8.0"
    - name: Install tox
      run: pip install tox
    - name: Run tests using tox
      run: tox
    - name: Upload code coverage report
      uses: actions/upload-artifact@v1
      with:
        name: coverage-report
        path: htmlcov
    - name: Upload pytest report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: pytest-report
        path: unittest-report